language: node_js
node_js:
- '8'

before_install:
  - stty cols 80

env:
  global:
  - secure: L5vNGeb6J1ny0hZ4GX5DzC4usAswY6tm6mNHURiry1O+mHA5J44I6ORjere7fumK+DMnP/7SM5TjZ54kyjgP5sfp1U713atCxjhxL4rxgCDQy9mPQkrVohubmpuzlkTGjW1N/dWLUk3+HLSo+ze++DBpwryqxQxTenlkMAtVBDuTMbaLzJ+Nr2TLaqTLp053q9vBmM0c/VFL5kfFwUO/+pbVsScVL3c0B/KKPs0OMJKyjYRSH/m+5DBgB81meAZeSzS7vcvM8W1yKv1zTBW8fUQTh4+jWAIXWz8COSoeuPSA8yHax0UJ7CkqdlzZ8qT1+hKIIuiSSnlYGtET9/UUJPVeONk2sAHayfVqBqkQiD0m/cksaiiUYUUJf/4kcLjKMJWMAnbjRpUlhQFa+KJPbDVOVWyRrVmVpkrobGAmlU9gc1Ca+ceJ1ynLncixomYuZHcIV+RDX2eqZRxPw+FvcSAx5umzVAjHrKEEqa1m06V0aUWIozhXPIsUbWyc4Kx/tJ+qAMmOo8cohgmH+HWefeKxyVvwuiyI5xZZUigX0wMYFLim4bZS1s9C0ifhdBmKgJgcv0ZB0C+8IYavoMyfmnoMuDRpuTpoi7EDlcfhvs5Ec+VFUzMz2asA3aSDDsNnOun0RivWPG4uNCmYfrzCji4t4dYv0MIILBj9l7n9X2g=
dist: trusty
sudo: required
addons:
  firefox: stable
  chrome: stable

script:
- npm run build_dev
- npm run build_prod
deploy:
- provider: script
  script: chmod +x ./deploy_npm.sh && ./deploy_npm.sh
  skip_cleanup: true
  on:
    tags: true
